from pathlib import Path
import re


def rep(s, old, new, label):
    if old not in s:
        raise SystemExit(f'missing patch target: {label}')
    return s.replace(old, new, 1)

# INDEX
p=Path('index.html'); s=p.read_text()
old='''      <section class="admin-pane" data-admin-pane="moderation">\n        <div class="admin-block"><div class="admin-block-head"><div><b>MODERATION HISTORY</b><span>Private owner log. Ordinary bad taste is not a reset reason.</span></div></div><div id="adminModeration"></div></div>\n      </section>'''
opts='<option value="all">ALL SPOTS</option>'+''.join(f'<option value="{n}">SPOT {n:02d}</option>' for n in range(1,17))
new=f'''      <section class="admin-pane" data-admin-pane="moderation">\n        <div class="admin-block"><div class="admin-block-head admin-history-head"><div><b>SPOT HISTORY</b><span>Every replaced state is kept as lightweight metadata. Filter one square or view the whole audit trail.</span></div><select id="adminHistorySpotFilter" class="admin-history-filter">{opts}</select></div><div id="adminModeration"></div></div>\n      </section>'''
s=rep(s,old,new,'history filter block')
s=s.replace('<script src="boot.js?v=16"></script>','<script src="boot.js?v=17"></script>')
p.write_text(s)

# JS
p=Path('takeover-v3.js'); s=p.read_text()
s=rep(s,"let editorCanvas=null,editorCreativeId=null,editorContext='purchase',editorSelected=null,editorCompany='',editorWebsite='',moderationSpot=null,refundAttempt=null,lastImpressionKey='';","let editorCanvas=null,editorCreativeId=null,editorContext='purchase',editorSelected=null,editorCompany='',editorWebsite='',moderationSpot=null,refundAttempt=null,lastImpressionKey='',adminHistorySpot='all',adminControlSpot=null;",'admin globals')

s=rep(s,'<button class="tiny danger" data-reset="${s.spot_number}" ${s.owner_key?\'\':\'disabled\'}>RESET</button>','<button class="tiny" data-control="${s.spot_number}">CONTROL</button>','board control button')
s=rep(s,"$$('[data-reset]').forEach(b=>b.onclick=()=>openReset(Number(b.dataset.reset)));","$$('[data-control]').forEach(b=>b.onclick=()=>openSpotControl(Number(b.dataset.control)));",'board control handler')

s=rep(s,'function wireAdminConsole(){','function wireAdminConsole(){wireSpotHistoryFilter();','wire history filter')
marker='async function adminConsoleCall(action,body={})'
insert="""function wireSpotHistoryFilter(){const f=$('#adminHistorySpotFilter');if(!f||f.dataset.wired)return;f.dataset.wired='1';f.value=String(adminHistorySpot);f.onchange=()=>{adminHistorySpot=f.value==='all'?'all':Number(f.value);renderModerationHistory()}}\n"""
s=rep(s,marker,insert+marker,'history filter helper')

# Replace the old moderation-only log with the complete spot state history.
pat=r"async function renderModerationHistory\(\)\{.*?\}\nasync function renderHealth"
newhist="""async function renderModerationHistory(){const box=$('#adminModeration');if(!box)return;let q=sb.from('takeover_spot_history').select('id,spot_number,event_type,event_note,current_price,company_name,website,owner_since,created_at').order('created_at',{ascending:false}).limit(100);if(adminHistorySpot!=='all')q=q.eq('spot_number',Number(adminHistorySpot));const {data,error}=await q;if(error){box.innerHTML=`<div class=\"empty\">${esc(error.message)}</div>`;return}const rows=data||[];box.innerHTML=rows.length?rows.map(h=>`<div class=\"admin-row history-audit-row\"><span>${String(h.spot_number).padStart(2,'0')}</span><div><b>${esc(h.company_name||'AVAILABLE')} · ${cash(h.current_price||0)}</b><small>${esc(String(h.event_type||'change').replaceAll('_',' ').toUpperCase())} · ${new Date(h.created_at).toLocaleString()}</small>${h.event_note?`<p>${esc(h.event_note)}</p>`:''}</div><button class=\"tiny\" data-history-control=\"${h.spot_number}\">CONTROL</button></div>`).join(''):'<div class=\"empty\">No history for this view yet.</div>';$$('[data-history-control]').forEach(b=>b.onclick=()=>openSpotControl(Number(b.dataset.historyControl)))}\nasync function renderHealth"""
s2,n=re.subn(pat,newhist,s,count=1,flags=re.S)
if n!=1: raise SystemExit('missing patch target: moderation history function')
s=s2

# Full per-spot admin control surface.
marker='async function renderAdmin(){'
control=r'''function ensureSpotControlModal(){if($('#spotControlModal'))return;const p=document.createElement('section');p.id='spotControlModal';p.className='panel modal spot-control-modal';p.innerHTML=`<div class="panel-inner"><div class="panel-head"><div><span>OWNER CONTROL</span><h2 id="spotControlTitle">Spot control.</h2></div><button class="close" id="spotControlClose">×</button></div><div id="spotControlCurrent"></div><div class="spot-control-grid"><div class="spot-control-card"><b>MARKET PRICE</b><span>Set the spot's stored price level directly. The normal +$${Number(config.min_increment||1)} takeover rule still applies afterward.</span><div class="spot-price-edit"><input id="adminSpotPrice" type="number" min="0" step="1"><button class="secondary" id="adminSetSpotPrice">SET PRICE</button></div></div><div class="spot-control-card"><b>CONTENT / OWNERSHIP</b><span>Separate content moderation from ownership and price when needed.</span><button class="secondary" id="adminHideSpotContent">HIDE CONTENT · KEEP OWNER</button><button class="secondary" id="adminVacateKeepPrice">VACATE · KEEP PRICE</button><button class="secondary danger" id="adminEmergencyReset">EMERGENCY RESET TO START</button></div></div><div class="field"><label>ADMIN NOTE · OPTIONAL</label><textarea id="adminSpotNote" maxlength="500" placeholder="Why are you making this change?"></textarea></div><div class="selector-title spot-history-title"><div><b>RESTORE HISTORY</b><small>Up to 100 lightweight states per spot. Recent displaced media stays protected for your configured retention window.</small></div></div><div id="spotControlHistory"><div class="empty">Loading history…</div></div></div>`;document.body.appendChild(p);$('#spotControlClose').onclick=closeSpotControl;$('#adminSetSpotPrice').onclick=setControlledSpotPrice;$('#adminHideSpotContent').onclick=hideControlledSpotContent;$('#adminVacateKeepPrice').onclick=vacateControlledSpot;$('#adminEmergencyReset').onclick=()=>{const n=adminControlSpot;closeSpotControl();if(n)openReset(n)}}
function closeSpotControl(){$('#spotControlModal')?.classList.remove('on');if($('#adminPanel')?.classList.contains('on'))$('#scrim')?.classList.add('on')}
async function openSpotControl(n){adminControlSpot=Number(n);ensureSpotControlModal();const s=spot(adminControlSpot);$('#spotControlTitle').textContent=`Spot ${String(adminControlSpot).padStart(2,'0')} control`;$('#spotControlCurrent').innerHTML=`<div class="spot-current-state"><span>CURRENT STATE</span><b>${esc(s.company_name||'AVAILABLE')}</b><strong>${s.current_price?cash(s.current_price):cash(config.starting_price)+' START'}</strong><small>${s.owner_key?'Owned since '+(s.owner_since?new Date(s.owner_since).toLocaleString():'—'):'No current owner'}${s.website?' · '+esc(host(s.website)):''}</small></div>`;$('#adminSpotPrice').value=Number(s.current_price||0);$('#adminSpotNote').value='';$('#adminHideSpotContent').disabled=!s.owner_key;$('#adminVacateKeepPrice').disabled=!s.owner_key;$('#adminEmergencyReset').disabled=!s.owner_key;await renderSpotControlHistory(adminControlSpot);openPanel('#spotControlModal')}
async function refreshSpotControl(msg){if(msg)toast(msg);await refreshBoard();await renderAdmin();if(adminControlSpot)await openSpotControl(adminControlSpot)}
async function setControlledSpotPrice(){if(!adminControlSpot)return;const price=Number($('#adminSpotPrice').value),note=$('#adminSpotNote').value.trim()||null;if(!Number.isFinite(price)||price<0)return toast('Enter a valid price');const {error}=await sb.rpc('admin_set_takeover_spot_price',{p_spot_number:adminControlSpot,p_price:price,p_note:note});if(error)return toast(error.message);await refreshSpotControl(`Spot ${adminControlSpot} price updated`)}
async function hideControlledSpotContent(){if(!adminControlSpot)return;const s=spot(adminControlSpot);if(!confirm(`Hide the public content on Spot ${String(adminControlSpot).padStart(2,'0')} while keeping its owner and ${cash(s.current_price)} price?`))return;const note=$('#adminSpotNote').value.trim()||null,{error}=await sb.rpc('admin_hide_takeover_spot_content',{p_spot_number:adminControlSpot,p_note:note});if(error)return toast(error.message);await refreshSpotControl(`Spot ${adminControlSpot} content hidden`)}
async function vacateControlledSpot(){if(!adminControlSpot)return;const s=spot(adminControlSpot),next=Number(s.current_price||0)+Number(config.min_increment||1);if(!confirm(`Vacate Spot ${String(adminControlSpot).padStart(2,'0')} but keep its ${cash(s.current_price)} market level? The next takeover will require ${cash(next)}.`))return;const note=$('#adminSpotNote').value.trim()||null,{error}=await sb.rpc('admin_vacate_takeover_spot',{p_spot_number:adminControlSpot,p_keep_price:true,p_note:note});if(error)return toast(error.message);await refreshSpotControl(`Spot ${adminControlSpot} vacated without resetting price`)}
async function restoreSpotHistory(id,row,fullMedia){const warning=fullMedia?'':`\n\nThis snapshot is older than the current ${config.storage_retention_days||30}-day media protection window. Text, owner and price can still restore, but an unused old image may already have been cleaned.`;if(!confirm(`Restore Spot ${String(row.spot_number).padStart(2,'0')} to ${row.company_name||'AVAILABLE'} at ${cash(row.current_price||0)}?${warning}`))return;const note=$('#adminSpotNote').value.trim()||null,{error}=await sb.rpc('admin_restore_takeover_spot',{p_history_id:id,p_note:note});if(error)return toast(error.message);await refreshSpotControl(`Spot ${row.spot_number} restored`)}
async function renderSpotControlHistory(n){const box=$('#spotControlHistory');if(!box)return;const {data,error}=await sb.from('takeover_spot_history').select('id,spot_number,event_type,event_note,current_price,company_name,website,logo_url,canvas_json,owner_since,created_at').eq('spot_number',n).order('created_at',{ascending:false}).limit(20);if(error){box.innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}const rows=data||[];box.innerHTML='';if(!rows.length){box.innerHTML='<div class="empty">No previous states yet. History starts with the next change to this spot.</div>';return}const windowMs=Number(config.storage_retention_days||30)*86400000;rows.forEach(h=>{const card=document.createElement('div');card.className='spot-history-card';const preview=document.createElement('div');preview.className='spot-history-preview';if(h.company_name||h.canvas_json)preview.appendChild(buildCanvasCreative({company_name:h.company_name||'PREVIOUS STATE',website:h.website||'',logo_url:h.logo_url||null,canvas_json:h.canvas_json},null,null,false));else preview.innerHTML='<span>AVAILABLE</span>';const meta=document.createElement('div');meta.className='spot-history-meta';const fullMedia=Date.now()-new Date(h.created_at).getTime()<=windowMs;meta.innerHTML=`<b>${esc(h.company_name||'AVAILABLE')} · ${cash(h.current_price||0)}</b><span>${esc(String(h.event_type||'change').replaceAll('_',' ').toUpperCase())} · ${new Date(h.created_at).toLocaleString()}</span><small class="${fullMedia?'history-safe':'history-aged'}">${fullMedia?'MEDIA PROTECTED':'OLDER MEDIA MAY BE CLEANED'}</small>${h.event_note?`<p>${esc(h.event_note)}</p>`:''}`;const restore=document.createElement('button');restore.type='button';restore.className='secondary';restore.textContent='RESTORE THIS STATE';restore.onclick=()=>restoreSpotHistory(h.id,h,fullMedia);card.append(preview,meta,restore);box.appendChild(card)})}

'''
s=rep(s,marker,control+marker,'spot control functions')
p.write_text(s)

# CSS
p=Path('takeover-v3.css'); s=p.read_text()
css=r'''
/* V21 owner spot-control + bounded history */
.admin-history-head{gap:18px;align-items:center}.admin-history-filter{min-width:160px;padding:11px 13px;border:1px solid rgba(17,17,17,.18);background:#fff;font:700 12px/1.2 Manrope,sans-serif;letter-spacing:.04em}.spot-control-modal{z-index:80}.spot-control-modal .panel-inner{max-width:900px}.spot-current-state{display:grid;grid-template-columns:1fr auto;gap:5px 18px;padding:18px;border:1px solid rgba(17,17,17,.14);margin-bottom:14px}.spot-current-state>span,.spot-current-state>small{grid-column:1/-1}.spot-current-state>span{font-size:10px;font-weight:800;letter-spacing:.12em}.spot-current-state>b{font-size:22px}.spot-current-state>strong{font-size:22px;text-align:right}.spot-current-state>small{opacity:.65}.spot-control-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0}.spot-control-card{display:flex;flex-direction:column;gap:9px;padding:16px;border:1px solid rgba(17,17,17,.14)}.spot-control-card>b{font-size:12px;letter-spacing:.08em}.spot-control-card>span{font-size:12px;line-height:1.45;opacity:.66;min-height:35px}.spot-price-edit{display:grid;grid-template-columns:1fr auto;gap:8px}.spot-price-edit input{min-width:0;padding:11px;border:1px solid rgba(17,17,17,.18);font:800 16px Manrope,sans-serif}.spot-history-title{margin-top:18px}.spot-history-card{display:grid;grid-template-columns:112px 1fr auto;gap:14px;align-items:center;padding:12px 0;border-top:1px solid rgba(17,17,17,.12)}.spot-history-preview{width:112px;aspect-ratio:1;overflow:hidden;border:1px solid rgba(17,17,17,.14);container-type:inline-size;display:grid;place-items:center;font-size:10px;font-weight:800}.spot-history-preview .canvas-creative{width:100%;height:100%;position:relative}.spot-history-meta{display:flex;flex-direction:column;gap:4px;min-width:0}.spot-history-meta>b{font-size:14px}.spot-history-meta>span,.spot-history-meta>p{font-size:11px;opacity:.68;margin:0}.spot-history-meta>small{width:max-content;padding:3px 6px;border:1px solid rgba(17,17,17,.14);font-size:9px;font-weight:800;letter-spacing:.06em}.history-aged{opacity:.55}.history-audit-row p{margin:4px 0 0;font-size:11px;opacity:.68}@media(max-width:700px){.admin-history-head{align-items:stretch;flex-direction:column}.admin-history-filter{width:100%}.spot-control-grid{grid-template-columns:1fr}.spot-history-card{grid-template-columns:76px 1fr}.spot-history-preview{width:76px}.spot-history-card>button{grid-column:1/-1;width:100%}.spot-current-state>b,.spot-current-state>strong{font-size:18px}}
'''
if 'V21 owner spot-control' not in s:s+=css
p.write_text(s)

# CACHE
p=Path('boot.js'); s=p.read_text().replace('takeover-v3.css?v=20','takeover-v3.css?v=21').replace('takeover-v3.js?v=20','takeover-v3.js?v=21'); p.write_text(s)

# CI
p=Path('.github/workflows/ci-v18.yml'); s=p.read_text()
s=s.replace('- name: V20 architecture','- name: V21 architecture')
s=s.replace("grep -q 'takeover-v3.js?v=20' boot.js","grep -q 'takeover-v3.js?v=21' boot.js")
s=s.replace("grep -q 'takeover-v3.css?v=20' boot.js","grep -q 'takeover-v3.css?v=21' boot.js")
s=s.replace("grep -q 'boot.js?v=16' index.html","grep -q 'boot.js?v=17' index.html")
marker='      - name: Typography interaction regression\n'
step='''      - name: Spot history and owner-control regression\n        run: |\n          grep -q 'takeover_spot_history' takeover-v3.js\n          grep -q 'admin_restore_takeover_spot' takeover-v3.js\n          grep -q 'admin_set_takeover_spot_price' takeover-v3.js\n          grep -q 'admin_vacate_takeover_spot' takeover-v3.js\n          grep -q 'admin_hide_takeover_spot_content' takeover-v3.js\n          grep -q 'adminHistorySpotFilter' index.html\n          grep -q 'data-control' takeover-v3.js\n          grep -q 'RESTORE THIS STATE' takeover-v3.js\n          echo 'PASS V21 SPOT CONTROL'\n'''
if step not in s:s=rep(s,marker,step+marker,'CI spot control step')
p.write_text(s)

print('V21 patch applied')
