(()=>{'use strict';
const SUPA_URL='https://xvfgiaxxvwdnmzzdfboc.supabase.co';
const SUPA_KEY='sb_publishable_ShdZijibR7b6EvowZ1yN9Q_dIkGmcCZ';
const sb=supabase.createClient(SUPA_URL,SUPA_KEY,{auth:{storageKey:'takeover-auth-v1',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const cash=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
const boardCols='spot_number,current_price,owner_key,company_name,website,logo_url,owner_since,updated_at';
let session=null,profile=null,isAdmin=false,spots=[],config={starting_price:10,min_increment:1,purchases_enabled:true,page_shield_until:null};
let mode='takeover',selected=[],bidLevels={},seedSpot=null,selectedLogoUrl=null,toastTimer=null,boardPoll=null,noticeChannel=null;

function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('on'),2800)}
function openPanel(id){const p=$(id);if(!p)return;$('#scrim').classList.add('on');p.classList.add('on')}
function closePanels(){$('#scrim').classList.remove('on');$$('.panel').forEach(x=>x.classList.remove('on'))}
$$('[data-close]').forEach(b=>b.onclick=closePanels);$('#scrim').onclick=closePanels;
function spot(n){return spots.find(x=>x.spot_number===Number(n))||{spot_number:Number(n),current_price:0,owner_key:null}}
function own(s){return !!(profile?.owner_key&&s?.owner_key===profile.owner_key)}
function minTake(s){return Number(s.current_price)>0?Number(s.current_price)+Number(config.min_increment):Number(config.starting_price)}
function normalizeWebsite(v){v=String(v||'').trim();if(v&&!/^https?:\/\//i.test(v))v='https://'+v;return v}
function host(v){try{return new URL(v).hostname.replace(/^www\./,'')}catch{return v||''}}
function neighbor(a,b){const ar=Math.floor((a-1)/4),ac=(a-1)%4,br=Math.floor((b-1)/4),bc=(b-1)%4;return Math.abs(ar-br)+Math.abs(ac-bc)===1}
function connected(arr){if(arr.length<2)return true;const seen=new Set([arr[0]]),q=[arr[0]];while(q.length){const a=q.shift();arr.forEach(b=>{if(!seen.has(b)&&neighbor(a,b)){seen.add(b);q.push(b)}})}return seen.size===arr.length}
function setLogoPreview(boxSelector,inputSelector,url,placeholder){const box=$(boxSelector),input=$(inputSelector);if(!box||!input)return;[...box.children].forEach(el=>{if(el!==input)el.remove()});const el=document.createElement(url?'img':'span');if(url){el.src=url;el.alt='Logo preview'}else el.textContent=placeholder;box.insertBefore(el,input)}

async function loadIdentity(){profile=null;isAdmin=false;if(!session)return;const [{data:p},{data:a}]=await Promise.all([sb.from('takeover_profiles').select('*').eq('user_id',session.user.id).maybeSingle(),sb.rpc('is_takeover_admin')]);profile=p||null;isAdmin=!!a}
async function refreshBoard(){const [{data:board,error},{data:cfg}]=await Promise.all([sb.from('takeover_spots').select(boardCols).order('spot_number'),sb.from('takeover_config').select('starting_price,min_increment,purchases_enabled,page_shield_until').eq('singleton',true).maybeSingle()]);if(error)return;spots=board||[];if(cfg)config=cfg;renderBoard();renderChrome()}
function startLiveUpdates(){if(boardPoll)clearInterval(boardPoll);boardPoll=setInterval(refreshBoard,5000);if(noticeChannel)sb.removeChannel(noticeChannel);noticeChannel=null;if(session){noticeChannel=sb.channel('takeover-alerts-'+session.user.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'takeover_notifications',filter:`user_id=eq.${session.user.id}`},p=>{toast(p.new?.title||'TAKEOVER alert');updateAlertBadge()}).subscribe()}}
async function loadState(){const [{data:sess},{data:cfg},{data:board}]=await Promise.all([sb.auth.getSession(),sb.from('takeover_config').select('starting_price,min_increment,purchases_enabled,page_shield_until').eq('singleton',true).maybeSingle(),sb.from('takeover_spots').select(boardCols).order('spot_number')]);session=sess.session;if(cfg)config=cfg;spots=board||[];await loadIdentity();renderBoard();renderChrome();startLiveUpdates();if(session)await updateAlertBadge();await handleReturn();const draft=readDraft();if(session&&draft)setTimeout(()=>restoreDraft(draft),180);if(!localStorage.getItem('takeover_intro_v1')&&!new URLSearchParams(location.search).has('takeover'))openPanel('#introModal')}

function shieldActive(){return !!config.page_shield_until&&new Date(config.page_shield_until).getTime()>Date.now()}
function ownsWholePage(){return spots.length===12&&spots.every(s=>own(s))}
function shieldBlocked(){return shieldActive()&&!ownsWholePage()}
function shieldRemaining(){if(!shieldActive())return'';let ms=Math.max(0,new Date(config.page_shield_until).getTime()-Date.now()),h=Math.floor(ms/3600000),m=Math.floor(ms/60000)%60,s=Math.floor(ms/1000)%60;return `${h}H ${m}M ${s}S`}
function renderChrome(){const account=$('#accountBtn');account.textContent=session?'MY SPOTS':'SIGN IN';$('#adminBtn').hidden=!isAdmin;const cost=spots.reduce((n,s)=>n+(own(s)?0:minTake(s)),0),page=$('#takePageBtn'),shield=$('#shieldFlag'),blocked=shieldBlocked();if(shield){shield.hidden=!shieldActive();if(shieldActive())shield.textContent=`FULL TAKEOVER · ${shieldRemaining()} PROTECTED`}page.textContent=ownsWholePage()?(shieldActive()?`PAGE PROTECTED · ${shieldRemaining()}`:'YOU OWN THE PAGE'):(blocked?'PAGE TAKEOVER PROTECTED':cost>0?`TAKE THE PAGE · ${cash(cost)}`:'YOU OWN THE PAGE');page.disabled=cost<=0||!config.purchases_enabled||blocked;$('#pauseFlag').hidden=config.purchases_enabled;if(session)$('#alertBtn').hidden=false;else $('#alertBtn').hidden=true}
function rectangles(){const groups=new Map();spots.filter(s=>s.owner_key).forEach(s=>{if(!groups.has(s.owner_key))groups.set(s.owner_key,[]);groups.get(s.owner_key).push(s.spot_number)});const out=[];for(const [key,nums] of groups){const remain=new Set(nums);while(remain.size){const start=[...remain].sort((a,b)=>a-b)[0],r=Math.floor((start-1)/4),c=(start-1)%4;let w=1;while(c+w<4&&remain.has(r*4+c+w+1))w++;let h=1,ok=true;while(r+h<3&&ok){for(let x=0;x<w;x++)if(!remain.has((r+h)*4+c+x+1)){ok=false;break}if(ok)h++}const cells=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++){const n=(r+y)*4+c+x+1;remain.delete(n);cells.push(n)}out.push({key,r,c,w,h,cells,ad:spot(start)})}}return out}
function renderBoard(){const grid=$('#gridLines'),acts=$('#spotActions'),terr=$('#territories');grid.innerHTML='';acts.innerHTML='';terr.innerHTML='';for(let n=1;n<=12;n++){const g=document.createElement('div');g.className='grid-cell';grid.appendChild(g);const s=spot(n),a=document.createElement('div');a.className='spot-action';if(!s.owner_key){const b=document.createElement('button');b.className='available-cell';b.innerHTML=shieldBlocked()?`<span>SPOT ${String(n).padStart(2,'0')}</span><b>PROTECTED</b>`:`<span>SPOT ${String(n).padStart(2,'0')}</span><b>TAKE FOR ${cash(minTake(s))}</b>`;b.disabled=shieldBlocked();b.onclick=()=>openTakeover(n);a.appendChild(b)}else{const b=document.createElement('button');b.className='take-pill';b.textContent=own(s)?`DEFEND · ${cash(Number(s.current_price)+Number(config.min_increment))}`:shieldBlocked()?'PROTECTED':`TAKE · ${cash(minTake(s))}`;b.disabled=!own(s)&&shieldBlocked();b.onclick=()=>own(s)?openDefend(n):openTakeover(n);a.appendChild(b)}acts.appendChild(a)}const rects=rectangles();rects.forEach(r=>{const s=r.ad,t=document.createElement('div');t.className='territory';t.style.left=(r.c*25)+'%';t.style.top=(r.r/3*100)+'%';t.style.width=(r.w*25)+'%';t.style.height=(r.h/3*100)+'%';t.innerHTML=`<a href="${esc(s.website||'#')}" target="_blank" rel="noopener sponsored">${s.logo_url?`<img src="${esc(s.logo_url)}" alt="${esc(s.company_name||'Advertiser')}">`:`<div class="wordmark">${esc(s.company_name||'TAKEOVER')}</div>`}<span class="site">${esc(host(s.website))}</span></a>`;terr.appendChild(t)});$('#board').classList.toggle('full-takeover',rects.length===1&&rects[0].cells.length===12)}

function fillBrandForm(){if(profile){$('#companyName').value=profile.company_name||'';$('#companyWebsite').value=profile.website||''}else{$('#companyName').value='';$('#companyWebsite').value=''}setLogoPreview('#logoPreview','#logoFile',selectedLogoUrl,'UPLOAD LOGO · OPTIONAL');const input=$('#logoFile');if(input)input.value=''}
function openTakeover(n){if(shieldBlocked())return toast(`Full-page takeover protected for ${shieldRemaining()}`);mode='takeover';seedSpot=n;selected=[n];bidLevels={[n]:minTake(spot(n))};selectedLogoUrl=profile?.logo_url||null;fillBrandForm();renderTakeover();openPanel('#takeoverModal')}
function openPage(){if(shieldBlocked())return toast(`Full-page takeover protected for ${shieldRemaining()}`);mode='takeover';seedSpot=null;selected=Array.from({length:12},(_,i)=>i+1);bidLevels={};selected.forEach(n=>bidLevels[n]=own(spot(n))?Number(spot(n).current_price):minTake(spot(n)));selectedLogoUrl=profile?.logo_url||null;fillBrandForm();renderTakeover();openPanel('#takeoverModal')}
function openDefend(n){if(!session){saveDraft();return openAuth()}mode='defend';seedSpot=n;selected=[n];bidLevels={[n]:Number(spot(n).current_price)+Number(config.min_increment)};selectedLogoUrl=profile?.logo_url||spot(n).logo_url||null;fillBrandForm();renderTakeover();openPanel('#takeoverModal')}
$('#takePageBtn').onclick=openPage;
function canAdd(n){return selected.length===0||selected.some(x=>neighbor(x,n))}
function toggleSelection(n){if(mode==='defend')return;if(selected.includes(n)){if(selected.length===1)return;const next=selected.filter(x=>x!==n);if(!connected(next))return toast('Keep selected spots connected');selected=next}else{if(!canAdd(n))return toast('New spots must touch your selection');selected=[...selected,n].sort((a,b)=>a-b);bidLevels[n]=own(spot(n))?Number(spot(n).current_price):minTake(spot(n))}renderTakeover()}
function renderTakeover(){$('#takeoverKicker').textContent=mode==='defend'?'DEFEND YOUR TERRITORY':selected.length===12?'FULL PAGE TAKEOVER':'TAKEOVER';$('#takeoverTitle').textContent=mode==='defend'?`Defend Spot ${seedSpot}`:selected.length===12?'Take the whole page.':selected.length>1?`Take ${selected.length} connected spots.`:`Take Spot ${selected[0]}.`;$('#territoryHint').textContent=mode==='defend'?'Raise your level. You only pay the difference.':'Add touching spots to make your ad larger. Your own cells cost $0 in a larger takeover.';const mini=$('#miniGrid');mini.innerHTML='';for(let n=1;n<=12;n++){const s=spot(n),sel=selected.includes(n),self=own(s),b=document.createElement('button');b.className='mini-spot'+(sel?' selected':'')+(self?' own':'');b.innerHTML=`<b>${String(n).padStart(2,'0')}</b>${self?'YOURS':cash(minTake(s))}`;if(mode==='defend')b.disabled=n!==seedSpot;else if(!sel&&!canAdd(n)&&selected.length!==11)b.disabled=true;b.onclick=()=>toggleSelection(n);mini.appendChild(b)}$('#selectAllBtn').hidden=mode==='defend'||selected.length===12;renderBids();renderCheckoutGate()}
$('#selectAllBtn').onclick=()=>{selected=Array.from({length:12},(_,i)=>i+1);selected.forEach(n=>bidLevels[n]=own(spot(n))?Number(spot(n).current_price):Math.max(Number(bidLevels[n]||0),minTake(spot(n))));renderTakeover()};
function renderBids(){const box=$('#bidRows');box.innerHTML='';selected.forEach(n=>{const s=spot(n),self=own(s),row=document.createElement('div');row.className='bid-row';if(mode==='takeover'&&self)row.innerHTML=`<span><b>Spot ${n}</b><small>Already yours — included free</small></span><b style="text-align:right">$0</b>`;else{const min=mode==='defend'?Number(s.current_price)+Number(config.min_increment):minTake(s);if(!bidLevels[n]||bidLevels[n]<min)bidLevels[n]=min;row.innerHTML=`<span><b>Spot ${n}</b><small>${mode==='defend'?`Current ${cash(s.current_price)} · you pay only the increase`:`Current ${s.current_price?cash(s.current_price):'available'} · minimum ${cash(min)}`}</small></span><input type="number" min="${min}" step="1" value="${Math.trunc(bidLevels[n])}" data-bid="${n}">`}box.appendChild(row)});$$('[data-bid]').forEach(i=>i.oninput=()=>{const n=Number(i.dataset.bid),s=spot(n),min=mode==='defend'?Number(s.current_price)+Number(config.min_increment):minTake(s);bidLevels[n]=Math.max(min,Math.trunc(Number(i.value)||0));renderTotal()});renderTotal()}
function totalDue(){return selected.reduce((sum,n)=>{const s=spot(n);if(mode==='takeover'&&own(s))return sum;if(mode==='defend')return sum+Math.max(0,Number(bidLevels[n])-Number(s.current_price));return sum+Number(bidLevels[n]||0)},0)}
function renderTotal(){$('#checkoutTotal').textContent=cash(totalDue());$('#checkoutBtn').disabled=!config.purchases_enabled||totalDue()<=0||shieldBlocked()}
function renderCheckoutGate(){$('#signinGate').hidden=!!session;$('#checkoutBtn').hidden=!session;$('#signedAs').hidden=!session;if(session)$('#signedAs').textContent=`Buying as ${session.user.email}`}
$('#continueSignin').onclick=()=>{saveDraft();closePanels();openAuth()};
$('#logoFile').onchange=e=>{const f=e.target.files?.[0];if(f)setLogoPreview('#logoPreview','#logoFile',URL.createObjectURL(f),'UPLOAD LOGO · OPTIONAL')};
async function uploadSpecificLogo(f){if(!f)return null;if(!session)throw new Error('Sign in first');if(f.size>2097152)throw new Error('Logo must be under 2 MB');if(!['image/png','image/jpeg','image/webp'].includes(f.type))throw new Error('Use PNG, JPG or WebP');const ext=f.type==='image/png'?'png':f.type==='image/webp'?'webp':'jpg',path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('takeover-logos').upload(path,f,{contentType:f.type,upsert:false});if(error)throw error;return sb.storage.from('takeover-logos').getPublicUrl(path).data.publicUrl}
async function uploadTakeoverLogo(){const f=$('#logoFile').files?.[0];if(!f)return selectedLogoUrl||profile?.logo_url||null;return uploadSpecificLogo(f)}
$('#checkoutBtn').onclick=async()=>{if(!session)return openAuth();if(!config.purchases_enabled)return toast('Purchases are paused');const company=$('#companyName').value.trim(),website=normalizeWebsite($('#companyWebsite').value);if(!company)return toast('Enter your company name');if(!website)return toast('Enter your website');const btn=$('#checkoutBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='OPENING STRIPE…';try{selectedLogoUrl=await uploadTakeoverLogo();const bids=selected.map(n=>mode==='takeover'&&own(spot(n))?Number(spot(n).current_price):Math.trunc(Number(bidLevels[n])));const {data,error}=await sb.functions.invoke('takeover-create-checkout',{body:{spot_numbers:selected,bid_levels:bids,company_name:company,website,logo_url:selectedLogoUrl,kind:mode}});if(error||data?.error)throw new Error(data?.error||error?.message||'Checkout failed');clearDraft();location.href=data.url}catch(e){toast(e.message);btn.disabled=false;btn.textContent=old}};

function draftData(){return{mode,selected,bidLevels,seedSpot,company:$('#companyName')?.value||'',website:$('#companyWebsite')?.value||'',logoUrl:selectedLogoUrl}}
function saveDraft(){if(!selected.length)return;try{localStorage.setItem('takeover_purchase_draft',JSON.stringify(draftData()))}catch{}}
function readDraft(){try{return JSON.parse(localStorage.getItem('takeover_purchase_draft')||'null')}catch{return null}}
function clearDraft(){localStorage.removeItem('takeover_purchase_draft')}
function restoreDraft(d){if(!d?.selected?.length)return;mode=d.mode||'takeover';selected=(d.selected||[]).map(Number);bidLevels=d.bidLevels||{};seedSpot=d.seedSpot||null;selectedLogoUrl=d.logoUrl||profile?.logo_url||null;fillBrandForm();$('#companyName').value=d.company||profile?.company_name||'';$('#companyWebsite').value=d.website||profile?.website||'';renderTakeover();openPanel('#takeoverModal')}

function openAuth(){if(session)return openAccount();$('#authEmail').value='';$('#authSent').hidden=true;openPanel('#authModal')}
$('#accountBtn').onclick=()=>session?openAccount():openAuth();
$('#sendMagicLink').onclick=async()=>{const email=$('#authEmail').value.trim();if(!email)return toast('Enter your email');const b=$('#sendMagicLink'),old=b.textContent;b.disabled=true;b.textContent='SENDING…';saveDraft();const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname,shouldCreateUser:true}});b.disabled=false;b.textContent=old;if(error)return toast(error.message);$('#authSent').hidden=false;$('#authSent').textContent=`Sign-in link sent to ${email}. Open it and you’ll come right back here.`};
$('#signOut').onclick=async()=>{await sb.auth.signOut();closePanels();toast('Signed out')};
sb.auth.onAuthStateChange((_e,s)=>{setTimeout(async()=>{session=s;await loadIdentity();renderChrome();startLiveUpdates();if(session)await updateAlertBadge();const d=readDraft();if(session&&d)restoreDraft(d)},0)});

async function openAccount(){await loadIdentity();await renderAccount();openPanel('#accountPanel')}
async function renderAccount(){$('#accountEmail').textContent=session?.user?.email||'';$('#accountCompany').value=profile?.company_name||'';$('#accountWebsite').value=profile?.website||'';setLogoPreview('#accountLogoPreview','#accountLogo',profile?.logo_url||null,'NO LOGO YET');const accountLogo=$('#accountLogo');if(accountLogo)accountLogo.value='';const mine=profile?spots.filter(s=>s.owner_key===profile.owner_key):[];$('#mySpots').innerHTML=mine.length?mine.map(s=>`<div class="my-spot"><div><b>Spot ${String(s.spot_number).padStart(2,'0')} · ${cash(s.current_price)}</b><small>Yours since ${s.owner_since?new Date(s.owner_since).toLocaleDateString():'—'}</small></div><button class="tiny" data-defend="${s.spot_number}">DEFEND</button></div>`).join(''):'<div class="empty">You don’t own a spot yet.</div>';$$('[data-defend]').forEach(b=>b.onclick=()=>{closePanels();openDefend(Number(b.dataset.defend))});await renderAlerts()}
$('#saveBrand').onclick=async()=>{if(!session||!profile)return toast('Take your first spot to create a brand profile');const company=$('#accountCompany').value.trim(),website=normalizeWebsite($('#accountWebsite').value);if(!company||!website)return toast('Enter company and website');try{let logo=profile.logo_url;const f=$('#accountLogo').files?.[0];if(f)logo=await uploadSpecificLogo(f);const {error}=await sb.rpc('update_takeover_brand',{p_company_name:company,p_website:website,p_logo_url:logo});if(error)throw error;toast('Brand updated');await loadIdentity();await refreshBoard();await renderAccount()}catch(e){toast(e.message)}};
$('#accountLogo').onchange=e=>{const f=e.target.files?.[0];if(f)setLogoPreview('#accountLogoPreview','#accountLogo',URL.createObjectURL(f),'NO LOGO YET')};
async function renderAlerts(){if(!session)return;const {data}=await sb.from('takeover_notifications').select('*').order('created_at',{ascending:false}).limit(20),rows=data||[];$('#alerts').innerHTML=rows.length?rows.map(n=>`<div class="alert-row ${n.read_at?'':'unread'}"><b>${esc(n.title)}</b><p>${esc(n.body)}</p><small>${new Date(n.created_at).toLocaleString()}</small></div>`).join(''):'<div class="empty">No alerts yet.</div>';const unread=rows.filter(x=>!x.read_at);if(unread.length){await sb.from('takeover_notifications').update({read_at:new Date().toISOString()}).in('id',unread.map(x=>x.id));updateAlertBadge()}}
async function updateAlertBadge(){if(!session)return;const {count}=await sb.from('takeover_notifications').select('id',{count:'exact',head:true}).is('read_at',null),b=$('#alertBtn'),badge=$('#alertBadge');b.hidden=false;badge.hidden=!count;badge.textContent=count||0}
$('#alertBtn').onclick=()=>openAccount();

$('#introGotIt').onclick=()=>{localStorage.setItem('takeover_intro_v1','1');closePanels()};$('#rulesBtn').onclick=()=>openPanel('#rulesModal');$('#legalBtn').onclick=()=>openPanel('#rulesModal');
$('#adminBtn').onclick=async()=>{if(!isAdmin)return;await renderAdmin();openPanel('#adminPanel')};
async function renderAdmin(){$('#startingPrice').value=config.starting_price;$('#minIncrement').value=config.min_increment;$('#purchasesEnabled').checked=!!config.purchases_enabled;$('#adminBoard').innerHTML=spots.map(s=>`<div class="admin-row"><span>${String(s.spot_number).padStart(2,'0')}</span><div><b>${esc(s.company_name||'AVAILABLE')} · ${s.current_price?cash(s.current_price):cash(config.starting_price)}</b><small>${s.website?esc(host(s.website)):'No owner'}</small></div><button class="tiny danger" data-clear="${s.spot_number}" ${s.owner_key?'':'disabled'}>CLEAR</button></div>`).join('');$$('[data-clear]').forEach(b=>b.onclick=()=>clearAdminSpot(Number(b.dataset.clear)));const {data:attempts}=await sb.from('takeover_attempts').select('id,kind,status,company_name,total_amount,created_at').order('created_at',{ascending:false}).limit(20);$('#adminAttempts').innerHTML=(attempts||[]).map(a=>`<div class="admin-row"><span>•</span><div><b>${esc(a.company_name)} · ${cash(a.total_amount)}</b><small>${a.kind} · ${a.status} · ${new Date(a.created_at).toLocaleString()}</small></div></div>`).join('')||'<div class="empty">No purchases yet.</div>'}
$('#saveConfig').onclick=async()=>{const payload={starting_price:Math.max(1,Math.trunc(Number($('#startingPrice').value)||10)),min_increment:Math.max(1,Math.trunc(Number($('#minIncrement').value)||1)),purchases_enabled:$('#purchasesEnabled').checked,updated_at:new Date().toISOString()};const {error}=await sb.from('takeover_config').update(payload).eq('singleton',true);if(error)return toast(error.message);config={...config,...payload};toast('TAKEOVER settings saved');renderChrome();renderBoard()};
async function clearAdminSpot(n){if(!confirm(`Clear Spot ${n}? This removes the ad and resets its price. It does not automatically refund prior purchases.`))return;const {error}=await sb.rpc('admin_clear_takeover_spot',{p_spot_number:n});if(error)return toast(error.message);toast(`Spot ${n} cleared`);await refreshBoard();await renderAdmin()}

async function handleReturn(){const q=new URLSearchParams(location.search),state=q.get('takeover'),attempt=q.get('attempt');if(!state)return;if(state==='cancel')toast('Checkout cancelled — nothing changed');if(state==='success'){toast('Payment received — claiming your territory…');if(session&&attempt)await pollAttempt(attempt)}history.replaceState({},'',location.pathname)}
async function pollAttempt(id){for(let i=0;i<15;i++){const {data}=await sb.from('takeover_attempts').select('status,failure_reason').eq('id',id).maybeSingle();if(data?.status==='won'){toast('You own it. Welcome to the page.');clearDraft();await refreshBoard();return}if(data?.status==='refunded'){toast('The board changed during checkout. You were automatically refunded.');clearDraft();return}if(data?.status==='refund_failed'){toast('Payment needs review. No territory was assigned.');return}await new Promise(r=>setTimeout(r,900))}toast('Payment is still processing. Your account will update automatically.')}

let lastShield=false;setInterval(()=>{const active=shieldActive();renderChrome();if(lastShield&&!active)renderBoard();lastShield=active},1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshBoard()});window.addEventListener('focus',refreshBoard);
loadState().catch(e=>toast(e.message));
})();