/* DOM-level regression checks. These do not substitute for rendered browser QA. */
const {JSDOM}=require('jsdom');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const errors=[],writes=[];
const dom=new JSDOM(html,{url:'https://takeoverspot.com/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;
w.addEventListener('error',e=>errors.push(e.error));
w.ResizeObserver=class{observe(){} disconnect(){}};
w.matchMedia=()=>({matches:false,addEventListener(){}});
w.localStorage.setItem('takeover_intro_v2','1');
w.HTMLElement.prototype.scrollTo=function(p){this.scrollLeft=p.left||0;this.scrollTop=p.top||0;};
w.HTMLElement.prototype.scrollBy=function(x,y){this.scrollLeft+=x;this.scrollTop+=y;};
const art={version:1,display:'combined',frameCells:[1,2,5],bg:{type:'solid',color:'#123456'},layers:[{id:'title',type:'text',text:'REAL DESIGN',x:10,y:20,w:80,h:20,size:24,font:'heavy',color:'#ffffff'}]};
const spots=Array.from({length:16},(_,i)=>({spot_number:i+1,current_price:10,owner_key:[1,2,5].includes(i+1)?'owner-1':null,creative_id:[1,2,5].includes(i+1)?'creative-1':null,company_name:'Example Brand',website:'https://example.com',canvas_json:art}));
let config={starting_price:10,min_increment:1,purchases_enabled:true,page_shield_until:null};
function query(table){
  const q=new Proxy({},{get:(_,key)=>key==='then'?(resolve)=>Promise.resolve({data:table==='takeover_spots'?spots:table==='takeover_config'?config:[],error:null}).then(resolve):()=>q});return q;
}
const sb={from:query,rpc:(name)=>{writes.push(name);return Promise.resolve({data:null,error:null});},auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange(){}},removeChannel(){},functions:{invoke:async()=>{throw Error('Unexpected remote function');}}};
w.supabase={createClient:()=>sb};
const board=d.getElementById('board');
Object.defineProperties(board,{clientWidth:{value:390,configurable:true},clientHeight:{value:640,configurable:true}});
w.eval(fs.readFileSync(path.join(root,'board-view.js'),'utf8'));
w.eval(fs.readFileSync(path.join(root,'canvas-presets.js'),'utf8'));
w.eval(fs.readFileSync(path.join(root,'takeover-v3.js'),'utf8'));
const tick=()=>new Promise(r=>setTimeout(r,70));
(async()=>{
  await tick();
  assert.equal(d.querySelectorAll('#spotActions>.spot-action').length,16);
  assert.equal(d.querySelectorAll('#gridLines>.grid-cell').length,16);
  assert.equal(d.querySelectorAll('#territories>.territory').length,1);
  assert.equal(d.querySelectorAll('#boardSurface>#territories').length,1);
  assert.equal(d.querySelectorAll('.board-app>header').length,1);
  assert.equal(d.querySelectorAll('.board-app>footer').length,1);
  assert.equal(d.getElementById('boardSurface').style.width,'390px');
  d.getElementById('boardExplore').click();
  assert.equal(d.getElementById('boardSurface').style.width,'640px');
  assert.equal(d.getElementById('boardNavigator').hidden,false);
  d.querySelector('#boardMap button:last-child').click();
  assert.ok(board.scrollLeft>0);
  d.getElementById('boardFit').click();
  assert.equal(d.getElementById('boardSurface').style.width,'390px');
  assert.equal(d.getElementById('boardNavigator').hidden,true);
  d.querySelector('.inspect-spot').click();
  assert.ok(d.getElementById('spotPreviewModal').classList.contains('on'));
  assert.equal(d.getElementById('spotPreviewTitle').textContent,'Example Brand');
  assert.match(d.getElementById('spotPreviewMeta').textContent,/01 · 02 · 05/);
  assert.match(d.getElementById('spotPreviewArt').style.clipPath,/takeover-frame/);
  assert.equal(d.querySelector('#spotPreviewArt .editor-content').textContent,'REAL DESIGN');
  assert.equal(d.querySelector('#spotPreviewActions a').href,'https://example.com/');
  d.querySelector('#spotPreviewActions .action').click();
  assert.ok(d.getElementById('takeoverModal').classList.contains('on'));
  assert.match(d.getElementById('checkoutTotal').textContent,/11/);
  d.getElementById('openPurchaseCanvas').click();await tick();
  assert.ok(d.getElementById('canvasModal').classList.contains('on'));
  assert.equal(d.querySelectorAll('#canvasPresets .preset-card').length,32);
  const originalBackground=d.getElementById('canvasStage').style.background;
  d.querySelector('[data-preset="event-horizon"]').click();
  const orbitalBackground=d.getElementById('canvasStage').style.background;
  assert.notEqual(orbitalBackground,originalBackground);
  assert.equal(d.getElementById('presetBrowser').open,false);
  assert.ok(d.getElementById('canvasStage').classList.contains('is-preview'));
  d.getElementById('canvasMotionToggle').click();
  assert.ok(d.getElementById('canvasStage').classList.contains('motion-paused'));
  d.getElementById('canvasUndo').click();
  assert.equal(d.getElementById('canvasStage').style.background,originalBackground);
  d.getElementById('canvasRedo').click();
  assert.equal(d.getElementById('canvasStage').style.background,orbitalBackground);
  [...d.querySelectorAll('.preset-filter')].find(b=>b.textContent==='Animated').click();
  assert.equal(d.querySelectorAll('#canvasPresets .preset-card').length,w.TakeoverPresets.catalog.filter(p=>p.motion!=='none').length);
  d.querySelector('#canvasLayerList button').click();
  assert.equal(d.getElementById('canvasStage').classList.contains('is-preview'),false);
  assert.ok(d.querySelector('#layerInspector input'));
  const secondColor=d.getElementById('bgColor2');secondColor.value='#aa2211';secondColor.dispatchEvent(new w.Event('input'));
  assert.match(d.getElementById('canvasStage').style.background,/170, 34, 17/);
  d.getElementById('canvasUndo').click();
  assert.equal(d.getElementById('canvasStage').style.background,orbitalBackground);
  const edited=d.querySelector('.editor-content');assert.ok(edited);
  d.getElementById('toggleCanvasPreview').click();
  assert.ok(d.querySelector('.canvas-preview-live .editor-content'));
  assert.ok(d.getElementById('canvasStage').classList.contains('is-preview'));
  d.getElementById('canvasClose').click();
  // Board refresh must retain the original frame after a competitor takes a cell.
  spots[1].owner_key=null;spots[1].creative_id=null;
  w.dispatchEvent(new w.Event('focus'));await tick();
  const territory=d.querySelector('#territories>.territory');
  assert.equal(territory.style.width,'50%');assert.equal(territory.style.height,'50%');
  const cp=d.getElementById('takeover-frame-1-2-5--1-5');assert.equal(cp.children.length,2);
  assert.equal(cp.children[0].getAttribute('width'),'0.5');
  config={...config,purchases_enabled:false};
  w.dispatchEvent(new w.Event('focus'));await tick();
  assert.ok([...d.querySelectorAll('#spotActions .available-cell,#spotActions .take-pill')].every(b=>b.disabled));
  assert.equal(errors.length,0,errors.map(String).join('\n'));
  assert.ok(writes.every(x=>x==='record_takeover_impressions'),'Navigation must not change ownership or payments');
  console.log('PASS: board navigation, combined artwork, preview-to-purchase, editor preview, partial takeover, paused controls.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>w.close());
