import { storageReferences } from "../_shared/storage-references.ts";
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function cronAllowed(req:Request,admin:any){const got=req.headers.get('X-Takeover-Cron')||'';if(!got)return false;const {data,error}=await admin.from('takeover_worker_secret').select('secret').eq('singleton',true).maybeSingle();return !error&&!!data?.secret&&safeEqual(got,String(data.secret))}
function pathFromUrl(value:string,bucket:string){const marker=`/storage/v1/object/public/${bucket}/`,i=value.indexOf(marker);if(i<0)return null;try{return decodeURIComponent(value.slice(i+marker.length).split(/[?#]/)[0])}catch{return value.slice(i+marker.length).split(/[?#]/)[0]}}
function collect(value:any,bucket:string,out:Set<string>){if(!value)return;if(typeof value==='string'){const p=pathFromUrl(value,bucket);if(p)out.add(p);return}if(Array.isArray(value)){for(const v of value)collect(v,bucket,out);return}if(typeof value==='object')for(const v of Object.values(value))collect(v,bucket,out)}
async function listPage(store:any,prefix:string){const all:any[]=[];for(let offset=0;;offset+=1000){const {data,error}=await store.list(prefix,{limit:1000,offset,sortBy:{column:'name',order:'asc'}});if(error)throw error;const page=data||[];all.push(...page);if(page.length<1000)break}return all}
async function listBucket(admin:any,bucket:string){const store=admin.storage.from(bucket),all:any[]=[],root=await listPage(store,'');for(const item of root){if(item.id){all.push({...item,path:item.name});continue}const children=await listPage(store,item.name);for(const child of children)if(child.id)all.push({...child,path:item.name+'/'+child.name})}return all}
async function scan(admin:any){const {days,cutoff,spots,profiles,attempts,saved,history}=await storageReferences(admin);const report:any={retention_days:days,total_objects:0,total_bytes:0,orphan_objects:0,orphan_bytes:0,orphans:{}};for(const bucket of ['takeover-logos','takeover-creative']){const refs=new Set<string>();for(const row of [...spots,...profiles,...attempts,...history])collect(row,bucket,refs);for(const row of saved){const owned=new Set<string>();collect({logo_url:row.logo_url,canvas_json:row.canvas_json},bucket,owned);for(const p of owned)if(p.startsWith(String(row.user_id)+'/'))refs.add(p)}const files=await listBucket(admin,bucket),orphans:any[]=[];for(const f of files){const size=Number(f.metadata?.size||f.metadata?.contentLength||0);report.total_objects++;report.total_bytes+=size;const when=new Date(f.created_at||f.updated_at||0).getTime();if(when&&when<cutoff&&!refs.has(f.path)){orphans.push({path:f.path,size});report.orphan_objects++;report.orphan_bytes+=size}}report.orphans[bucket]=orphans}return report}
Deno.serve(async(req:Request)=>{if(req.method!=='POST')return json({error:'Method not allowed'},405);const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});if(!(await cronAllowed(req,admin)))return json({error:'Unauthorized'},401);try{const body=await req.json().catch(()=>({})),action=String(body?.action||'cleanup'),report=await scan(admin);if(action==='scan')return json({ok:true,...report,orphans:undefined});let deleted=0,deleted_bytes=0;for(const bucket of ['takeover-logos','takeover-creative']){const rows=report.orphans[bucket]||[];for(let i=0;i<rows.length;i+=100){const chunk=rows.slice(i,i+100),paths=chunk.map((x:any)=>x.path);if(!paths.length)continue;const {error}=await admin.storage.from(bucket).remove(paths);if(error)throw error;deleted+=paths.length;deleted_bytes+=chunk.reduce((n:number,x:any)=>n+Number(x.size||0),0)}}return json({ok:true,deleted,deleted_bytes,retention_days:report.retention_days,scanned:report.total_objects,remaining_orphan_candidates:Math.max(0,report.orphan_objects-deleted)})}catch(e){console.error('takeover-storage-worker',e);return json({ok:false,error:e instanceof Error?e.message:'Storage worker failed'},500)}});

