import { manageAccount } from "../_shared/account-management.ts";
import { storageReferences } from "../_shared/storage-references.ts";
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const allowedOrigins=new Set(['https://takeoverspot.com','https://www.takeoverspot.com']);
function cors(req:Request){const o=req.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':allowedOrigins.has(o)?o:'https://takeoverspot.com','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'}}
const json=(req:Request,b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(req),'Content-Type':'application/json','Cache-Control':'no-store'}});
function cleanUuid(v:unknown){const s=String(v||'');return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s)?s:''}
function pathFromUrl(value:string,bucket:string){const marker=`/storage/v1/object/public/${bucket}/`;const i=value.indexOf(marker);if(i<0)return null;try{return decodeURIComponent(value.slice(i+marker.length).split(/[?#]/)[0])}catch{return value.slice(i+marker.length).split(/[?#]/)[0]}}
function collect(value:any,bucket:string,out:Set<string>){if(!value)return;if(typeof value==='string'){const p=pathFromUrl(value,bucket);if(p)out.add(p);return}if(Array.isArray(value)){for(const v of value)collect(v,bucket,out);return}if(typeof value==='object'){for(const v of Object.values(value))collect(v,bucket,out)}}
async function listPage(store:any,prefix:string){const all:any[]=[];for(let offset=0;;offset+=1000){const result=await store.list(prefix,{limit:1000,offset,sortBy:{column:'name',order:'asc'}});if(result.error)throw result.error;const page=result.data||[];all.push(...page);if(page.length<1000)break}return all}
async function listBucket(admin:any,bucket:string){const store=admin.storage.from(bucket);const all:any[]=[];const root=await listPage(store,'');for(const item of root){if(item.id){all.push({...item,path:item.name});continue}const children=await listPage(store,item.name);for(const child of children){if(child.id)all.push({...child,path:item.name+'/'+child.name})}}return all}
async function storageScan(admin:any,includeAll=false){const {days,cutoff,spots,profiles,attempts,saved,history}=await storageReferences(admin);const out:any={retention_days:days,total_objects:0,total_bytes:0,orphan_objects:0,orphan_bytes:0,buckets:{},orphans:{}};for(const bucket of ['takeover-logos','takeover-creative']){const refs=new Set<string>();for(const row of [...spots,...profiles,...attempts,...history])collect(row,bucket,refs);for(const row of saved){const owned=new Set<string>();collect({logo_url:row.logo_url,canvas_json:row.canvas_json},bucket,owned);for(const p of owned)if(p.startsWith(String(row.user_id)+'/'))refs.add(p)}const files=await listBucket(admin,bucket);const orphans:any[]=[];let bytes=0,orphanBytes=0;for(const f of files){const size=Number(f.metadata?.size||f.metadata?.contentLength||0);bytes+=size;const when=new Date(f.created_at||f.updated_at||0).getTime();if(when&&when<cutoff&&!refs.has(f.path)){orphans.push({path:f.path,size,created_at:f.created_at||f.updated_at});orphanBytes+=size}}out.total_objects+=files.length;out.total_bytes+=bytes;out.orphan_objects+=orphans.length;out.orphan_bytes+=orphanBytes;out.buckets[bucket]={objects:files.length,bytes,orphans:orphans.length,orphan_bytes:orphanBytes};out.orphans[bucket]=includeAll?orphans:orphans.slice(0,500)}return out}
async function logEvent(admin:any,userId:string,action:string,details:any={}){try{await admin.from('takeover_admin_events').insert({admin_user_id:userId,action,details})}catch{}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return json(req,{error:'Method not allowed'},405);try{const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const auth=req.headers.get('Authorization')||'';const jwt=auth.startsWith('Bearer ')?auth.slice(7):'';if(!jwt)return json(req,{error:'Sign in required'},401);const {data:ud,error:ue}=await admin.auth.getUser(jwt);const user=ud?.user;if(ue||!user)return json(req,{error:'Sign in required'},401);const {data:owner,error:oe}=await admin.from('spot_owners').select('user_id').single();if(oe||!owner||owner.user_id!==user.id)return json(req,{error:'Owner access required'},403);const body=await req.json().catch(()=>({}));const action=String(body?.action||'overview');
if(['account_status','account_disable','account_restore','account_delete'].includes(action))return json(req,await manageAccount(admin,user.id,body));
if(action==='overview'){const all=await Promise.all([admin.auth.admin.listUsers({page:1,perPage:1000}),admin.from('takeover_attempts').select('status,total_amount,created_at'),admin.from('takeover_refunds').select('status,amount'),admin.from('takeover_spots').select('owner_key,owner_user_id'),admin.from('takeover_email_outbox').select('status'),admin.from('takeover_admin_events').select('action,details,created_at').order('created_at',{ascending:false}).limit(15),admin.from('spot_owners').select('user_id',{count:'exact',head:true}),storageScan(admin,false)]);const usersResult:any=all[0],attempts=(all[1] as any).data||[],refunds=(all[2] as any).data||[],spots=(all[3] as any).data||[],emails=(all[4] as any).data||[],events=(all[5] as any).data||[],ownersResult:any=all[6],storage:any=all[7];const won=attempts.filter((x:any)=>x.status==='won');const gross=won.reduce((n:number,x:any)=>n+Number(x.total_amount||0),0);const refunded=refunds.filter((x:any)=>x.status==='succeeded').reduce((n:number,x:any)=>n+Number(x.amount||0),0);const stuck=attempts.filter((x:any)=>['created','checkout_open','stale','refund_failed'].includes(x.status)&&Date.now()-new Date(x.created_at).getTime()>20*60000).length;return json(req,{ok:true,overview:{users:usersResult.data?.users?.length||0,attempts:attempts.length,won:won.length,gross,refunded,occupied:spots.filter((x:any)=>x.owner_key).length,failed_emails:emails.filter((x:any)=>x.status==='failed').length,stuck_attempts:stuck,admin_count:ownersResult.count||0},storage,events});}
if(action==='users'){const search=String(body?.search||'').trim().toLowerCase();const page=Math.max(1,Math.trunc(Number(body?.page||1)));const perPage=Math.max(10,Math.min(100,Math.trunc(Number(body?.per_page||50))));const lr=await admin.auth.admin.listUsers({page:search?1:page,perPage:search?1000:perPage});let users=lr.data?.users||[];if(search)users=users.filter((u:any)=>String(u.email||'').toLowerCase().includes(search));const ids=users.map((u:any)=>u.id);if(!ids.length)return json(req,{ok:true,users:[]});const parts=await Promise.all([admin.from('takeover_profiles').select('user_id,company_name,website').in('user_id',ids),admin.from('takeover_spots').select('owner_user_id').in('owner_user_id',ids),admin.from('takeover_attempts').select('user_id,status,total_amount,created_at').in('user_id',ids)]);const profiles=(parts[0] as any).data||[],spots=(parts[1] as any).data||[],attempts=(parts[2] as any).data||[];const pmap=new Map(profiles.map((p:any)=>[p.user_id,p]));return json(req,{ok:true,users:users.slice(0,100).map((u:any)=>{const a=attempts.filter((x:any)=>x.user_id===u.id),owned=spots.filter((x:any)=>x.owner_user_id===u.id).length,won=a.filter((x:any)=>x.status==='won');return{id:u.id,email:u.email||'',created_at:u.created_at,last_sign_in_at:u.last_sign_in_at,disabled:new Date(u.banned_until||0).getTime()>Date.now(),is_owner:u.id===user.id,company:(pmap.get(u.id) as any)?.company_name||'',website:(pmap.get(u.id) as any)?.website||'',owned_spots:owned,purchases:a.length,won:won.length,spent:won.reduce((n:number,x:any)=>n+Number(x.total_amount||0),0),last_purchase:a.sort((x:any,y:any)=>new Date(y.created_at).getTime()-new Date(x.created_at).getTime())[0]?.created_at||null}})});}
if(action==='storage_scan')return json(req,{ok:true,storage:await storageScan(admin,false)});
if(action==='storage_cleanup'){const report=await storageScan(admin,true);let deleted=0,deletedBytes=0;for(const bucket of ['takeover-logos','takeover-creative']){const rows=report.orphans[bucket]||[];for(let i=0;i<rows.length;i+=100){const chunk=rows.slice(i,i+100),paths=chunk.map((x:any)=>x.path);if(!paths.length)continue;const {error}=await admin.storage.from(bucket).remove(paths);if(error)throw error;deleted+=paths.length;deletedBytes+=chunk.reduce((n:number,x:any)=>n+Number(x.size||0),0)}}await logEvent(admin,user.id,'storage_cleanup',{deleted,deleted_bytes:deletedBytes,retention_days:report.retention_days});return json(req,{ok:true,deleted,deleted_bytes:deletedBytes,retention_days:report.retention_days});}
if(action==='events'){const {data,error}=await admin.from('takeover_admin_events').select('action,details,created_at').order('created_at',{ascending:false}).limit(100);if(error)throw error;return json(req,{ok:true,events:data||[]});}
if(action==='user_detail'){const id=cleanUuid(body?.user_id);if(!id)return json(req,{error:'Invalid user'},400);const parts=await Promise.all([admin.from('takeover_profiles').select('company_name,website,created_at,updated_at').eq('user_id',id).maybeSingle(),admin.from('takeover_spots').select('spot_number,current_price,company_name,website,owner_since').eq('owner_user_id',id).order('spot_number'),admin.from('takeover_attempts').select('id,kind,status,total_amount,created_at,paid_at').eq('user_id',id).order('created_at',{ascending:false}).limit(50),admin.from('takeover_notifications').select('type,title,created_at').eq('user_id',id).order('created_at',{ascending:false}).limit(20)]);return json(req,{ok:true,profile:(parts[0] as any).data||null,spots:(parts[1] as any).data||[],attempts:(parts[2] as any).data||[],notifications:(parts[3] as any).data||[]});}
return json(req,{error:'Unknown admin action'},400)}catch(e){console.error('takeover-admin-console',e);return json(req,{error:e instanceof Error?e.message:'Admin console failed'},500)}});

